"use client";
import { useEffect, useState } from "react";
import { createClient, SupabaseClient } from "@supabase/supabase-js";
const logoUrl = "https://raw.githubusercontent.com/martiola68/studio-manager-pro/main/public/LogoSMP_.png";
let supabaseClient: SupabaseClient | null = null;
function getSupabaseClient() { if (typeof window === "undefined") throw new Error("Supabase può essere inizializzato solo nel browser."); if (supabaseClient) return supabaseClient; const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if(!u||!k) throw new Error("Configurazione Supabase non disponibile."); return supabaseClient=createClient(u,k); }
type SubscriptionData={ragione_sociale:string;piano:string;stato:string;stripe_status:string|null;prossimo_pagamento:string|null;can_manage_payment:boolean;can_reactivate:boolean;contract_end:string|null;automatic_renewal:boolean;cancellation_scheduled:boolean;deletion_status:string|null;deletion_requested_at:string|null;deletion_scheduled_at:string|null;service_ended_at:string|null;can_request_deletion:boolean;can_cancel_deletion:boolean;deletion_feature_ready?:boolean};
function Brand(){return <span className="brand"><img src={logoUrl} alt="" className="brandLogo"/><span className="brandWords"><strong>Studio Manager Pro</strong><small>Sistema Gestionale Integrato</small></span></span>}
export default function GestioneAbbonamentoPage(){
 const[data,setData]=useState<SubscriptionData|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[action,setAction]=useState("");
 async function token(){const a=sessionStorage.getItem("smp_subscription_access_token"),r=sessionStorage.getItem("smp_subscription_refresh_token"),s=getSupabaseClient();if(a&&r){const{x,error:e}= {x:await s.auth.setSession({access_token:a,refresh_token:r}),error:null} as any;const restored=x; if(!restored.error&&restored.data.session?.access_token){sessionStorage.setItem("smp_subscription_access_token",restored.data.session.access_token);if(restored.data.session.refresh_token)sessionStorage.setItem("smp_subscription_refresh_token",restored.data.session.refresh_token);return restored.data.session.access_token;}}const{data:d}=await s.auth.getSession();if(!d.session?.access_token)throw new Error("Sessione scaduta. Effettua nuovamente l’accesso.");return d.session.access_token;}
 async function load(){const t=await token(),r=await fetch("/api/abbonamento/stato",{headers:{Authorization:`Bearer ${t}`}}),j=await r.json();if(!r.ok)throw new Error(j?.error||"Impossibile caricare l’abbonamento");setData(j)}
 useEffect(()=>{(async()=>{try{await load()}catch(e:any){setError(e?.message||"Accesso non valido")}finally{setLoading(false)}})()},[]);
 async function post(kind:string,method="POST"){setAction(kind);setError("");setMessage("");try{const t=await token(),r=await fetch(`/api/abbonamento/${kind}`,{method,headers:{Authorization:`Bearer ${t}`}}),j=await r.json();if(!r.ok)throw new Error(j?.error||"Operazione non disponibile");if(j?.url){window.location.href=j.url;return}await load();return j}catch(e:any){setError(e?.message||"Operazione non riuscita")}finally{setAction("")}}
 async function disdetta(){if(!window.confirm(`Vuoi disdire il rinnovo? Il servizio resterà attivo fino alla scadenza contrattuale ${data?.contract_end?new Date(data.contract_end).toLocaleDateString("it-IT"):"annuale"}.`))return;await post("disdetta");setMessage("Disdetta registrata. Il servizio resta attivo fino alla scadenza contrattuale e non si rinnoverà automaticamente.")}
 async function deletion(){if(!window.confirm("Vuoi richiedere l’eliminazione definitiva di tutti i dati dello studio? La richiesta è distinta dalla disdetta e prevede 30 giorni di sicurezza."))return;await post("richiedi-cancellazione");setMessage("Richiesta registrata. I dati saranno eliminati definitivamente dopo il periodo di sicurezza, salvo annullamento.")}
 const next=data?.prossimo_pagamento?new Date(data.prossimo_pagamento).toLocaleDateString("it-IT"):"—",end=data?.contract_end?new Date(data.contract_end).toLocaleDateString("it-IT"):"—";
 return <main><header className="topbar"><a href="/"><Brand/></a><nav><a href="/">Sito</a><a href="/offerte">Offerte</a><a href="/accesso">Aree di accesso</a><a className="reservedLink" href="https://app.studiomanagerpro.it/login">Gestionale ↗</a></nav></header>
 <section className="heroV2" style={{minHeight:700}}><div className="heroGlow one"/><div className="heroGlow two"/><div className="heroMain"><p className="eyebrow lightEyebrow">AREA ABBONAMENTO</p><h1>Il tuo piano.<br/><em>Sotto controllo.</em></h1><p className="heroLead">{data?.ragione_sociale||"Gestisci abbonamento, pagamenti e continuità del servizio."}</p>{loading&&<p style={{color:"#c2d2e6"}}>Caricamento…</p>}{error&&<div style={errorStyle}>{error}</div>}{message&&<div style={successStyle}>{message}</div>}{data&&<><div className="heroProof"><span>Piano {data.piano}</span><i/><span>{data.stato}</span><i/><span>{data.stripe_status||"—"}</span></div><div className="heroActions" style={{marginTop:34}}>{data.can_manage_payment&&<button className="primaryButton whiteButton" style={buttonStyle} onClick={()=>post("portale")} disabled={!!action}>Aggiorna pagamento →</button>}{data.can_reactivate&&<button className="primaryButton" style={buttonStyle} onClick={()=>post("riattiva")} disabled={!!action}>Riattiva abbonamento →</button>}</div></>}</div><div className="productStage" style={{minHeight:500,padding:34}}><div className="stageGrid"/><div style={{position:"relative",zIndex:2}}><p className="eyebrow lightEyebrow">IL TUO ABBONAMENTO</p><h2 style={{fontSize:34}}>Stato del servizio</h2><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Info label="Piano" value={data?.piano||"—"}/><Info label="Pagamento" value={data?.stripe_status||"—"}/><Info label="Prossimo addebito" value={next}/><Info label="Scadenza contratto" value={end}/></div></div></div></section>
 {data&&<section className="statement"><p className="eyebrow">DURATA E DISDETTA</p><h2>Contratto annuale.<br/>Pagamento mensile.</h2><div className="statementText" style={{alignItems:"start"}}><div><p>La sottoscrizione ha durata annuale. Il pagamento mensile rappresenta la rateizzazione del corrispettivo annuale. La disdetta impedisce il rinnovo alla scadenza senza interrompere anticipatamente il periodo contrattuale in corso.</p><p style={{marginTop:18}}>Scadenza attuale: <strong>{end}</strong>.</p></div><div style={panelStyle}>{data.cancellation_scheduled?<><h3>Rinnovo disattivato</h3><p>Il servizio resterà disponibile fino al {end}.</p><button className="primaryButton" style={buttonStyle} onClick={()=>post("disdetta","DELETE")} disabled={!!action}>Riattiva rinnovo automatico</button></>:<><h3>Disdetta del rinnovo</h3><p>Puoi comunicare ora la disdetta. L’accesso resta attivo fino alla scadenza annuale.</p><button style={dangerStyle} onClick={disdetta} disabled={!!action}>Disdici alla scadenza →</button></>}</div></div></section>}
 {data&&<section className="statement"><p className="eyebrow">PRIVACY E DATI</p><h2>Eliminazione dei dati.<br/>Una scelta separata dalla disdetta.</h2><div className="statementText" style={{alignItems:"start"}}><div><p>La cessazione dell’abbonamento non elimina automaticamente i dati. L’amministratore può richiedere espressamente la cancellazione definitiva dell’intero ambiente dello studio.</p><p style={{marginTop:18}}>La richiesta prevede 30 giorni di sicurezza durante i quali può essere revocata.</p></div><div style={panelStyle}>{!data.deletion_feature_ready?<><h3>Funzione in attivazione</h3><p>La struttura applicativa è pronta; deve essere applicata la migration database prima di abilitare il comando.</p></>:data.can_cancel_deletion?<><h3>Cancellazione programmata</h3><p>Data prevista: <strong>{data.deletion_scheduled_at?new Date(data.deletion_scheduled_at).toLocaleDateString("it-IT"):"—"}</strong></p><button className="primaryButton" style={buttonStyle} onClick={()=>post("annulla-cancellazione")} disabled={!!action}>Annulla cancellazione</button></>:<><h3>Elimina tutti i dati</h3><p>Operazione destinata ai casi di cessazione o disdetta. Non coincide con la semplice sospensione del servizio.</p><button style={dangerStyle} onClick={deletion} disabled={!!action}>Richiedi eliminazione di tutti i dati →</button></>}</div></div></section>}
 <section className="securitySection" style={{paddingTop:20}}><div className="securityPanel"><p className="eyebrow">ACCESSO PROTETTO</p><h2>Una gestione separata dal gestionale.</h2><p>Anche se il servizio è sospeso, quest’area resta disponibile con email, password e codice fiscale dell’amministratore.</p></div></section>
 <footer style={{width:"min(1240px,calc(100% - 48px))",margin:"0 auto",padding:"28px 0 38px"}}>© 2026 Studio Manager Pro. Creato da Artiola Mario.</footer></main>}
const buttonStyle={border:0,cursor:"pointer"} as const,errorStyle={marginTop:20,padding:14,borderRadius:9,color:"#fecaca",background:"rgba(220,38,38,.16)"} as const,successStyle={marginTop:20,padding:14,borderRadius:9,color:"#c9f6df",background:"rgba(22,163,74,.14)"} as const,panelStyle={padding:28,background:"#f3f7fb",border:"1px solid #dce5ef",borderRadius:14} as const,dangerStyle={display:"inline-flex",minHeight:54,padding:"0 22px",alignItems:"center",color:"white",background:"#a62318",border:0,borderRadius:9,fontWeight:850,cursor:"pointer"} as const;
function Info({label,value}:{label:string;value:string}){return <div style={{minHeight:105,padding:18,background:"rgba(12,45,81,.82)",border:"1px solid rgba(119,190,239,.22)",borderRadius:12}}><span style={{display:"block",color:"#6fd3ff",fontSize:10,fontWeight:900,textTransform:"uppercase"}}>{label}</span><strong style={{display:"block",marginTop:18,color:"white",fontSize:18}}>{value}</strong></div>}
